---
apiVersion: v1
kind: Service
metadata:
  name: jicofo
spec:
  selector:
    app: jicofo
  ports:
    - port: 8888
      targetPort: 8888
      name: "port-8888"
  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jicofo
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#spec:
#  selector:
#    app: jicofo
#  ports:
#    - port: 8888
#      targetPort: 8888
#      name: "port-8888"
#  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jicofo-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  labels:
    app: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      volumes:
      - name: jicofo-config
        persistentVolumeClaim:
          claimName: jicofo-config-pvc
#      hostAliases:
#      - ip: ""
#        hostnames:
#        - "prosody"
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: 
        - "sh"
        - "-c"
        - "chown -R 999:1000 /config; chmod -R 777 /config;"
        # user:group - jicofo:jitsi - 999:1000
        volumeMounts:
        - mountPath: /config
          name: jicofo-config
      containers:
      - name: jicofo
        image: jitsi/jicofo
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /config
          name: jicofo-config
        envFrom:
          - configMapRef:
              name: jitsi-config
#        readinessProbe:
#          httpGet:
#            path: /about/health
#            port: 8888
#            initialDelaySeconds: 5
#            periodSeconds: 3
#            timeoutSeconds: 60
#        livenessProbe:
#          httpGet:
#            path: /about/health
#            port: 8888
#            initialDelaySeconds: 10
#            periodSeconds: 3        
        ports:
        - containerPort: 8888
      restartPolicy: Always

