#apiVersion: v1
#kind: Service
#metadata:
#  name: jicofo
#spec:
#  selector:
#    app: jicofo
#  ports:
#    - port: 8888
#      targetPort: 8888
#      name: "port-8888"
#  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jicofo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
  labels:
    app: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jicofo
  template:
    metadata:
      labels:
        app: jicofo
    spec:
      volumes:
      - name: jicofo-config
        persistentVolumeClaim:
          claimName: jicofo-pvc
      containers:
      - name: jicofo
        image: jitsi/jicofo
        volumeMounts:
        - mountPath: /config
          name: jicofo-config
        env:
        - name: ENABLE_AUTH
          value: ""
        - name: XMPP_DOMAIN
          value: "meet.jitsi"
        - name: XMPP_AUTH_DOMAIN
          value: "auth.meet.jitsi"
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: "internal-muc.meet.jitsi"
        - name: XMPP_SERVER
          value: "xmpp.meet.jitsi"
        - name: JICOFO_COMPONENT_SECRET
          value: "s3cr37"
        - name: JICOFO_AUTH_USER
          value: "focus"
        - name: JICOFO_AUTH_PASSWORD
          value: "passw0rd"
        - name: JVB_BREWERY_MUC
          value: "jvbbrewery"
        - name: JIGASI_BREWERY_MUC
          value: "jigasibrewery"
        - name: TZ
          value: "Europe/Amsterdam"
#        ports:
#        - containerPort: 8888

