---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jvb-tcp
#  labels:
#    app: jvb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#spec:
#  selector:
#    app: jvb
#  ports:
#  - name: "port-$JVB_TCP_PORT"
#    port: $JVB_TCP_PORT
#    targetPort: $JVB_TCP_PORT
#  type: LoadBalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jvb-udp
#  labels:
#    app: jvb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#spec:
#  selector:
#    app: jvb
#  ports:
#  - name: "port-$JVB_PORT"
#    port: $JVB_PORT
#    protocol: UDP
#    targetPort: $JVB_PORT
#  type: LoadBalancer
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jvb
#  labels:
#    app: jvb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#spec:
#  selector:
#    app: jvb
#  ports:
#  - name: "port-$JVB_PORT"
#    port: $JVB_PORT
#    protocol: UDP
#    targetPort: $JVB_PORT
#  - name: "port-$JVB_TCP_PORT"
#    port: $JVB_TCP_PORT
#    targetPort: $JVB_TCP_PORT
#  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: jvb
  labels:
    app: jvb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: jvb
  ports:
  - name: "port-$JVB_PORT"
    port: $JVB_PORT
    protocol: UDP
    targetPort: $JVB_PORT
  - name: "port-$JVB_TCP_PORT"
    port: $JVB_TCP_PORT
    targetPort: $JVB_TCP_PORT
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jvb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
  labels:
    app: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvb
  template:
    metadata:
      labels:
        app: jvb
    spec:
      volumes:
      - name: jvb-config
        persistentVolumeClaim:
          claimName: jvb-pvc
      hostAliases:
      - ip: "$XMPP_SERVER_ADDRESS"
        hostnames:
        - "$XMPP_SERVER"
      containers:
      - name: jvb
        image: jitsi/jvb
        volumeMounts:
        - mountPath: /config
          name: jvb-config
        env:
        - name: DOCKER_HOST_ADDRESS
          value: "$DOCKER_HOST_ADDRESS"
        - name: XMPP_AUTH_DOMAIN
          value: "$XMPP_AUTH_DOMAIN"
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: "$XMPP_INTERNAL_MUC_DOMAIN"
        - name: XMPP_SERVER
          value: "$XMPP_SERVER"
        - name: JVB_AUTH_USER
          value: "$JVB_AUTH_USER"
        - name: JVB_AUTH_PASSWORD
          value: "$JVB_AUTH_PASSWORD"
        - name: JVB_BREWERY_MUC
          value: "$JVB_BREWERY_MUC"
        - name: JVB_PORT
          value: "$JVB_PORT"
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "$JVB_TCP_HARVESTER_DISABLED"
        - name: JVB_TCP_PORT
          value: "$JVB_TCP_PORT"
        - name: JVB_STUN_SERVERS
          value: "$JVB_STUN_SERVERS"
        - name: JVB_ENABLE_APIS
          value: "$JVB_ENABLE_APIS"
        - name: JICOFO_AUTH_USER
          value: "$JICOFO_AUTH_USER"
        - name: TZ
          value: "$TZ"
        ports:
        - containerPort: $JVB_PORT
          protocol: UDP
        - containerPort: $JVB_TCP_PORT

