apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f qwe
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jicofo
  name: jicofo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jicofo
    spec:
      containers:
      - image: jitsi/jicofo
        name: jicofo
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: jicofo-claim0
      restartPolicy: Always
      volumes:
      - name: jicofo-claim0
        persistentVolumeClaim:
          claimName: jicofo-claim0
status: {}
