apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f qwe
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jvb
    spec:
      containers:
      - image: jitsi/jvb
        name: jvb
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 4443
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: jvb-claim0
      restartPolicy: Always
      volumes:
      - name: jvb-claim0
        persistentVolumeClaim:
          claimName: jvb-claim0
status: {}
