apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f qwe
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
    targetPort: 10000
  - name: "4443"
    port: 4443
    targetPort: 4443
  selector:
    io.kompose.service: jvb
status:
  loadBalancer: {}
