apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f qwe
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: jitsi/web
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: web-claim0
        - mountPath: /etc/letsencrypt
          name: web-claim1
        - mountPath: /usr/share/jitsi-meet/transcripts
          name: web-claim2
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: web-claim1
        persistentVolumeClaim:
          claimName: web-claim1
      - name: web-claim2
        persistentVolumeClaim:
          claimName: web-claim2
status: {}
