apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f qwe
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  - name: "8443"
    port: 8443
    targetPort: 443
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
